version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: ["docker-compose", "-f", "Frontend/docker-compose.yml", "up"]

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    env_file:
      - ./Backend/.env
    depends_on:
      - rag
    command: ["docker-compose", "-f", "Backend/docker-compose.yml", "up"]

  rag:
    build:
      context: ./RAG
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - llm
    command: ["docker-compose", "-f", "RAG/docker-compose.yml", "up"]

  llm:
    build:
      context: ./LLM
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    command: ["docker-compose", "-f", "LLM/docker-compose.yml", "up"]
